### PR TITLE
Hello CircleCI

### PR DESCRIPTION
**Pull request by quippo**
To set up CI

### CODE REVIEW

**Comment by chaspy** [comment]
Sorry I created this PR with wrong user 🙇

**Comment by chaspy** [comment]
- ✅ Set up CircleCI https://circleci.com/gh/quipper/workflows/td-agent
- [ ] Waiting for https://github.com/quipper/circleci/pull/296 to be merged

**Comment by chaspy** [comment]
CI pass ✅ 
https://circleci.com/gh/quipper/td-agent/3

@quipper/sre @quipper/data-engineers 
Please review and merge

**Comment by quippo** [comment]
### From CircleCI

:white_check_mark: Command exited with code 0

```sh
./scripts/deploy.sh
```

**Comment by chaspy** [comment]
✅ 
Screenshot 2019-07-11 17 58 11
https://cloud.docker.com/u/quipper/repository/docker/quipper/td-agent

**Pull request merged**
